// GENERATED by tools/paklist/genlevels.py -- do not hand-edit.
// Level names come from the pak's file index; they exist nowhere in the
// executable, so they cannot be discovered at runtime.
#pragma once

namespace sifucoop::levels {

struct Level {
    const char* category;
    const char* name;
    const char* package;
};

inline constexpr Level kLevels[] = {
    {"Arena", "Dancefloor", "/Game/Maps/TU_3/H2_Arenas/DanceFloor/Arena_Dancefloor_Main"},
    {"Arena", "The Corridor", "/Game/Maps/TU_3/H1_Arenas/H1_TheCorridor/Arena_TheCorridor_main"},
    {"Arena", "The Exposition", "/Game/Maps/TU_3/H3_Arenas/TheExposition/Arena_TheExposition_Main"},
    {"Arena", "The Hangar", "/Game/Maps/TU_3/H1_Arenas/The_Hangar/Arena_TheHangar_Main"},
    {"Arena", "The Kitchen", "/Game/Maps/TU_3/H5_Arenas/TheKitchen/Arena_TheKitchen_Main"},
    {"Arena", "The Park", "/Game/Maps/TU_3/H5_Arenas/ThePark/Arena_ThePark_Main"},
    {"Arena", "The Parking", "/Game/Maps/TU_3/H2_Arenas/TheParking/Arena_TheParking_Main"},
    {"Arena", "The Pit", "/Game/Maps/TU_3/H2_Arenas/The_Pit/Arena_ThePit_Main"},
    {"Arena", "The Rain", "/Game/Maps/TU_3/H3_Arenas/TheRain/Arena_TheRain_main"},
    {"Arena", "The Red Room", "/Game/Maps/TU_3/RedRoom/Arena_TheRedRoom_main"},
    {"Arena", "The Rooftop", "/Game/Maps/TU_3/H4_Arenas/TheRooftop/Arena_TheRooftop_main"},
    {"Arena", "The Server Room", "/Game/Maps/TU_3/H4_Arenas/TheServerRoom/Arena_TheServerRoom_main"},
    {"Arena", "The Snow Garden", "/Game/Maps/TU_3/H3_Arenas/TheSnowGarden/Arena_TheSnowGarden_main"},
    {"Arena", "The Stairs", "/Game/Maps/TU_3/H1_Arenas/H1_TheStairs/Arena_TheStairs_Main"},
    {"Arena", "The Wuguan", "/Game/Maps/TU_3/TheWuguan/Arena_TheWuguan_main"},
    {"Story", "Hideout 0", "/Game/Maps/Hideout0/Hideout_0_Main"},
    {"Story", "Hideout 1", "/Game/Maps/Hideout1/Hideout_1_Main"},
    {"Story", "Hideout 2", "/Game/Maps/Hideout2/Hideout_2_Main"},
    {"Story", "Hideout 3", "/Game/Maps/Hideout3/Hideout_3_Main"},
    {"Story", "Hideout 4", "/Game/Maps/Hideout4/Hideout_4_Main"},
    {"Story", "Hideout 5", "/Game/Maps/Hideout5/Hideout_5_main"},
    {"Other", "Opening", "/Game/Maps/Opening/Opening_Main"},
    {"Other", "Post Credits", "/Game/Maps/PostCredits/PostCredits_Main"},
    {"Other", "Training Room", "/Game/Maps/TrainingRoom/TrainingRoom_Main"},
    {"Other", "Wuguan", "/Game/Maps/Wuguan/Wuguan_Main"},
};

inline constexpr int kLevelCount = sizeof(kLevels) / sizeof(kLevels[0]);

}  // namespace sifucoop::levels
