"""Turn the enumerated .umap list into a level table for the mod.

Only "_Main" maps are travel targets -- everything else in the pak is a
streaming sublevel that OpenLevel cannot meaningfully load on its own.

Usage:
    python genlevels.py <levels.txt> <out levels.g.h>
"""

import re
import sys


def to_package_path(pak_path):
    """Sifu/Content/Maps/X/Y.umap -> /Game/Maps/X/Y"""
    path = pak_path
    if path.startswith("Sifu/Content/"):
        path = "/Game/" + path[len("Sifu/Content/") :]
    return path[: -len(".umap")] if path.endswith(".umap") else path


def display_name(package_path):
    leaf = package_path.rsplit("/", 1)[-1]
    leaf = re.sub(r"_[Mm]ain$", "", leaf)
    leaf = leaf.replace("Arena_", "")
    # CamelCase and underscores -> spaced words.
    leaf = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", leaf).replace("_", " ")
    return " ".join(w for w in leaf.split() if w)


def category(package_path):
    if "/TU_3/" in package_path:
        return "Arena"
    if "/Hideout" in package_path:
        return "Story"
    return "Other"


def main():
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8") as fh:
        maps = [line.strip() for line in fh if line.strip().lower().endswith("_main.umap")]

    entries = []
    for pak_path in sorted(maps):
        package = to_package_path(pak_path)
        entries.append((category(package), display_name(package), package))

    order = {"Arena": 0, "Story": 1, "Other": 2}
    entries.sort(key=lambda e: (order.get(e[0], 9), e[1]))

    lines = [
        "// GENERATED by tools/paklist/genlevels.py -- do not hand-edit.",
        "// Level names come from the pak's file index; they exist nowhere in the",
        "// executable, so they cannot be discovered at runtime.",
        "#pragma once",
        "",
        "namespace sifucoop::levels {",
        "",
        "struct Level {",
        "    const char* category;",
        "    const char* name;",
        "    const char* package;",
        "};",
        "",
        "inline constexpr Level kLevels[] = {",
    ]
    for cat, name, package in entries:
        lines.append(f'    {{"{cat}", "{name}", "{package}"}},')
    lines += [
        "};",
        "",
        "inline constexpr int kLevelCount = sizeof(kLevels) / sizeof(kLevels[0]);",
        "",
        "}  // namespace sifucoop::levels",
    ]

    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {dst} with {len(entries)} levels")
    for cat, name, package in entries:
        print(f"  [{cat:5}] {name:20} {package}")


if __name__ == "__main__":
    main()
